> /Users/ilgeehong/Desktop/SemGCon/Ours/hyperparameter.py(144)<module>()
-> wandb.agent(sweep_id, main(wandb.config))

(Pdb) wandb.agent(sweep_id, main(wandb.config))
*** KeyError: 'n_experiments'

(Pdb) exit
Traceback (most recent call last):
  File "/Users/ilgeehong/Desktop/SemGCon/Ours/hyperparameter.py", line 144, in <module>
    wandb.agent(sweep_id, main(wandb.config))
  File "/Users/ilgeehong/Desktop/SemGCon/Ours/hyperparameter.py", line 144, in <module>
    wandb.agent(sweep_id, main(wandb.config))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/bdb.py", line 113, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit